finalproject/blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog import views

urlpatterns = [

 
        url(r'(?P<id>\d+)/post_edit/$', views.post_edit, name="post_edit"),
    url(r'(?P<id>\d+)/post_delete/$', views.post_delete, name="post_delete"),
    url(r'(?P<id>\d+)/favourite_post/$', views.favorite_post, name="favorite_post"),
    url(r'(?P<id>\d+)/(?P<slug>[\w-]+)/$', views.post_detail, name="post_detail"),
    url(r'post_create/$', views.post_create, name="post_create"),
    url(r'edit_profile/$', views.edit_profile, name="edit_profile"),
     url(r'favorites/$', views.post_favorite_list, name="post_favorite_list"),
       url(r'favorites/$', views.post_favorite_list, name="post_favorite_list"),
      url(r'contact/$', views.contact, name="contact"),
   url(r'users/$', views.usersprofile, name="usersprofile"),






]

finalproject/finalproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

#urlpatterns = [
 #   url(r'^admin/', admin.site.urls),
  #  url(r'^$',views.user_login,name='user_login'),

   # url(r'^blog/',include('blog.urls',namespace='blog')),
   # url(r'^post/$',views.post_list,name='post_list'),
   # url(r'^logout/$',views.user_logout,name='user_logout'),

    #url(r'^password-reset/$', auth_views.password_reset, name="password_reset"),
     #url(r'^password-reset/done/$', auth_views.password_reset_done, name="password_reset_done"),
     #url(r'^password-reset/confirm/(?P<uidb64>[\w-]+)/(?P<token>[\w-]+)/$', auth_views.password_reset_confirm, name="password_reset_confirm"),
     #url(r'^password-reset/complete/$', auth_views.password_reset_complete, name="password_reset_complete"),
    #url(r'^register/$',views.register,name='register'),
     #url(r'^user/',views.usersprofile,name='usersprofile'),
    #url(r'^like/',views.like_post,name='like_post'),


urlpatterns = [

     url(r'^admin/', admin.site.urls),
    url(r'^$', views.post_list, name="post_list"),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^login/$', views.user_login, name="user_login"),
     url(r'^contact/$', views.contact, name="contact"),
    url(r'^logout/$', views.user_logout, name="user_logout"),
    url(r'^register/$', views.register, name="register"),

    # Password Reset Url's
    # url(r'^password-reset/$', auth_views.password_reset, name="password_reset"),
    # url(r'^password-reset/done/$', auth_views.password_reset_done, name="password_reset_done"),
    # url(r'^password-reset/confirm/(?P<uidb64>[\w-]+)/(?P<token>[\w-]+)/$', auth_views.password_reset_confirm, name="password_reset_confirm"),
    # url(r'^password-reset/complete/$', auth_views.password_reset_complete, name="password_reset_complete"),

  #  url(r'^', include('django.contrib.auth.urls')),
   # url(r'^oauth/', include('social_django.urls', namespace="social")),
    url(r'^like/', views.like_post, name="like_post"),





]




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finalproject/blog/models.py
from __future__ import unicode_literals
from django.db import models
from django.urls import reverse
from django.dispatch import receiver
from django.utils.text import slugify
from django.db.models.signals import pre_save

from  django.contrib.auth.models import User
def upload_location(instance,filename):
    return "%s/%s" %(instance.id,filename)
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status="published")
class Posts(models.Model):
    objects = models.Manager()      #Our default Manager
    published = PublishedManager()
    STATUS_CHOICES=(
        ('draft','Draft'),
        ('published','Published'),


    )
    title=models.CharField(max_length=100)
    slug=models.CharField(max_length=200)
    author=models.ForeignKey(User,related_name='blog_post')
    likes=models.ManyToManyField(User,related_name='likes',blank=True)
    image=models.ImageField(upload_to=upload_location,blank=True)
    body=models.TextField(max_length=1000)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    status=models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    favorite=models.ManyToManyField(User, related_name='favourite',blank=True)

    def __str__(self):
        return self.title
    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse("blog:post_detail",args=[self.id,self.slug])
@receiver(pre_save,sender=Posts)
def pre_save_slug(sender,**kwargs):
    slug=slugify(kwargs['instance'].title)
    kwargs['instance'].slug=slug

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField(null=True, blank=True)
    photo = models.ImageField(null=True, blank=True)


    def __str__(self):
        return "Profile of user {}".format(self.user.username)
class Contact(models.Model):
    fullname=models.CharField(max_length=100)
    email=models.EmailField(max_length=100)
    contact=models.CharField(max_length=20)
    message=models.TextField(max_length=500)

finalproject/blog/forms.py
from .models import *
from django import forms
from django.contrib.auth.models import User
class PostCreateForms(forms.ModelForm):
    class Meta:
        model=Posts
        fields=['title','body','status','image']

class UserLoginForm(forms.Form):
    username=forms.CharField(label="Enter your Username")
    password=forms.CharField(label="Enter your Password")


class PostEditForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields = (
            'title',
            'body',
            'image',
            'status',


        )

class UserRegistrationForm(forms.ModelForm):

    password=forms.CharField(label='Enter your Password')
    confirm_password=forms.CharField(label='Enter your Password')

    class Meta:
        model=User
        fields=('username','first_name','last_name','email')
        widgets={
            'username':forms.TextInput(attrs={'class':'input'}),
            'first_name':forms.TextInput(attrs={'class':'input'}),
             'last_name':forms.TextInput(attrs={'class':'input'}),
             'email':forms.TextInput(attrs={'class':'input'}),





        }

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password != confirm_password:
            raise forms.ValidationError("Password Mismatch")
        return confirm_password
class UserEditForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    boi=forms.CharField(widget=forms.Textarea(attrs={'class':'input'}))
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'boi',
        )


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model=Profile
        exclude=('user',)

class Contact(forms.ModelForm):
    email = forms.CharField(widget=forms.TextInput())
    class Meta:
        model=Contact
        fields=['fullname','email','contact','message']

finalproject/blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse,HttpResponseRedirect,Http404
from .models import Posts,Profile
from django.db.models import Q
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from .forms import *
from django.contrib import messages


def post_list(request):
    post=Posts.published.all().order_by("-updated")
    query=request.GET.get("q")
    users = User.objects.all()
    if query:
        post = Posts.published.filter(
        Q(title__icontains=query)|
        Q(author__username=query)|
        Q(body__icontains=query)
        )
    context={'post':post,
             'users':users,
            }
    return render(request,'blog/post_list.html',context)

def post_detail(request,slug,id):
    post=get_object_or_404(Posts,id=id,slug=slug)
    #post = get_object_or_404(Posts, id=request.POST.get('id'))
    is_liked = False
    is_favorite = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True
    if post.favorite.filter(id=request.user.id).exists():
        is_favorite = True



    context={ 'post': post,
        'is_liked': is_liked,
        'is_favorite': is_favorite,
        'total_likes': post.total_likes(),
       }
    return render(request,'blog/post_detail.html',context)
def like_post(request):
    post=get_object_or_404(Posts,id=request.POST.get('post_id'))
    is_liked=False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked=False
    else:
        post.likes.add(request.user)
        is_liked=True

    return HttpResponseRedirect(post.get_absolute_url())

def contact(request):
    if request.method=='POST':
        form=Contact(request.POST)
        if form.is_valid():
            post=form.save(commit=False)
            post.author=request.user
            post.save()

    else:
        form=Contact()

    context={'form':form,}

    return render(request,'blog/contact_form.html',context)

def post_create(request):
    if request.method=='POST':
        form=PostCreateForms(request.POST)
        if form.is_valid():
            post=form.save(commit=False)
            post.author=request.user
            post.save()

    else:
        form=PostCreateForms()

    context={'form':form,}

    return render(request,'blog/post_create.html',context)

def user_login(request):
    if request.method=='POST':
        form=UserLoginForm(request.POST)
        if form.is_valid():
           username=request.POST['username']
           password=request.POST['password']
           user=authenticate(username=username,password=password)
           if user:
               if user.is_active:
                   login(request,user)
                   return HttpResponseRedirect(reverse('post_list'))
               else:
                   return HttpResponseRedirect(reverse('user_login'))
           else:
               return HttpResponseRedirect(reverse('user_login'))
    else:
        form=UserLoginForm()
    context={'form':form,}
    return render(request,'blog/login.html',context)

def user_logout(request):
    logout(request)
    return redirect('user_login')

def register(request):
    if request.method=='POST':
        form=UserRegistrationForm(request.POST or None)
        if form.is_valid():
            new_user=form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            return  redirect('login')
    else:
        form=UserRegistrationForm()
    context={'form':form,}
    return render(request,'blog/register.html',context)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserEditForm(data=request.POST or None, instance=request.user)
        profile_form = ProfileEditForm(data=request.POST or None, instance=request.user.profile, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            print(profile_form)
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(reverse("blog:edit_profile"))
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
    }
    return render(request, 'blog/editprofile.html', context)

def usersprofile(request):
    post=Posts.published.all().order_by("-updated")
    post1=User.objects.all()
    query=request.GET.get("q")
    if query:
        post = Posts.published.filter(
        Q(title__icontains=query)|
        Q(author__username=query)|
        Q(body__icontains=query)
        )
    context={'post':post,
             'post1':post1,}
    return render(request,'blog/users.html',context)


def post_delete(request,id):
    post = get_object_or_404(Posts,id=id)
    if request.user != post.author:
        raise Http404()
    else:
       post.delete()
       messages.warning(request, 'post has been successfully deleted!')
       return redirect('post_list')

def post_favorite_list(request):
    user = request.user
    favorite_posts = user.favourite.all()
    context = {
        'favorite_posts': favorite_posts,
    }
    return render(request, 'blog/post_favorite.html', context)

def favorite_post(request, id):
    post = get_object_or_404(Posts, id=id)
    if post.favorite.filter(id=request.user.id).exists():
        post.favorite.remove(request.user)
    else:
        post.favorite.add(request.user)
    return HttpResponseRedirect(post.get_absolute_url())

def post_edit(request, id):
    post = get_object_or_404(Posts, id=id)
    if post.author != request.user:
        raise Http404()
    if request.method == "POST":
        form = PostEditForm(request.POST or None, instance=post)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        form = PostEditForm(instance=post)

    context = {
    'form': form,
    'post': post,

    }
    return render(request, 'blog/post_edit.html', context)

finalproject/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/bulma.css' %}">
    <script src="{% static 'js/navbar-burger.js' %}"></script>
</head>
<body>
<nav class="navbar">
    <div class="navbar-brand">
        <a href="/" class="navbar-item">
            <img src="http://bulma.io/images/bulma-logo.png" alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
        </a>
        <div class="navbar-burger burger" data-target="nav-data">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
        <div class="navbar-menu" id="nav-data">
            <a href="/" class="navbar-item">Home</a>
            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="field is-grouped">
                        <p class="control">
                            <a href="{% url 'register' %}" class="button is-primary">
                                <span>SIGN UP</span>
                            </a>
                        </p>
                    </div>
                </div>
        </div>
    </div>

</nav>
{% block heading %}  {% endblock %}

{%  block content %}

{%  endblock %}
</body>
</html>

finalproject/blog/templates/blog/contact_form.html
{% load static %}
<html lang="en" class="full-height">
<head>
    <style>

    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<link rel="stylesheet" href="{% static 'blog/login.css'%}" >
<body>
<!--Main Navigation-->


  <nav class="navbar navbar-dark bg-primary navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'post_list' %}">EduHub</a>
    </div>
  </div>
</nav>
<br>
<br>
<div class="container">
<div class="row">
    <div class="col-lg-6 col-centered">
<form  method="POST" class="border border p-2">
{% csrf_token %}
    <p class="h4 mb-4">FeedBack</p>

    <!-- Email -->
    <div class="label" >Full Name</div>
    {{form.fullname }}

    <div class="label" >Email</div>
    <br>
     {{form.email }}
    <br>
    <div class="label" >Contact</div>
    {{form.contact}}




    <div class="label" >Message</div>
     {{form.message }}







    <!-- Sign in button -->
    <button class="btn btn-info btn-block my-4" type="submit">Send</button>

</form>
</div>
    </div>

</div>
</body>

</html>

finalproject/blog/templates/blog/login.html
{% load static %}
<html lang="en" class="full-height">
<head>
    <style>

    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<link rel="stylesheet" href="{% static 'blog/login.css'%}" >
<body>
<!--Main Navigation-->


  <nav class="navbar navbar-dark bg-primary navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'post_list' %}">EduHub</a>
    </div>
  </div>
</nav>
<br>
<br>
<div class="container">
<div class="row">
    <div class="col-lg-6 col-centered">
<form  method="POST" class="border border p-4">
{% csrf_token %}
    <p class="h4 mb-4">Sign in</p>

    <!-- Email -->
    <label><b>Username</b></label>
    {{form.username }}

    <label><b>Password</b></label>
     {{form.password }}


    <div class="d-flex justify-content-around">

        <div>
            <!-- Forgot password -->
            <a href="">Forgot password?</a>
        </div>
    </div>

    <!-- Sign in button -->
    <button class="btn btn-info btn-block my-4" type="submit">Sign in</button>

    <!-- Register -->
    <p>Not a member?
        <a href="{% url 'register' %}">Register</a>
    </p>

    <!-- Social login -->

    <!-- Terms of service -->

</form>
</div>
    </div>

</div>
</body>

</html>

finalproject/blog/templates/blog/post_detail.html
{% load static %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" >
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'blog/style.css'%}" >
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

   <body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.2';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<a class="navbar-brand" href="{% url 'post_list' %}">EduHub</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="nav navbar-nav navbar-right">
    {% if request.user.is_authenticated %}

     <li class="dropdown">
      <a class="dropdown-toggle " href="#"  role="button" data-toggle="dropdown">


          <img src="/media/sagar123.png" alt="" class="navbar-img">

        <span>Hi {{ request.user|capfirst }}</span>
      <b class="caret"></b></a>
      <ul class="dropdown-menu"  >



         <li> <a  href="{% url 'blog:post_create' %}">Create Post</a></li>
              <li> <a  href="{% url 'blog:contact' %}">Report/FeedBack</a></li>

           <li> <a  href="{% url 'user_logout' %}">Sign out</a></li>
      </ul>
    </li>
     </ul>
    {% else %}
    <li class="nav-item">
      <a href="{% url 'user_login' %}" class="nav-link">Login</a>
    </li>
    {% endif %}
  </ul>
</div>
</nav>


    <div class="container-fluid gedf-wrapper ">
    </div>
        <div class="row">

            <div class="col-lg-10 gedf-main">
                <div class="card gedf-card ">
                    <div class="card-header ">
                     <div class="d-flex justify-content-between align-items-center">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="mr-2">

                                </div>

                            </div>
                            <div>
                                <div class="dropdown">
                                    {% if post.author == request.user %}
                                    <button class="btn btn-link dropdown-toggle" type="button" id="gedf-drop1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-ellipsis-h"></i>
                                    </button>

                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="gedf-drop1">
                                        <a class="dropdown-item" href="{% url 'blog:post_delete' id=post.id %}" >Delete</a>
                                        <a class="dropdown-item" href="{% url 'blog:post_edit' id=post.id %}">Edit Post</a>
                                        <a class="dropdown-item" href="{% url 'blog:favorite_post' id=post.id %}">Save</a>
                                    </div>


                                </div>
                                {% endif %}
                            </div>
                        </div>

                    </div>
                    <div class="card-body">


                        <h1 ><b>{{post.title|capfirst}}</b></h1>

                        <hr>

                        <p class="card-text">
                            {{post.body}}
                        </p>


                        {% if post.image %}

                      <img src='{{post.image.url}}'class="card-img"/>

                          {% endif %}
                    </div>
<div class="card-footer" >
<div class="fb-like" data-href="{{ request.build_absolute_url}}" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
    <hr>
     <div class="fb-comments" data-href="{{ request.build_absolute_url}}" data-numposts="5"></div>
    <!--div class="card-footer" >
 <div class="fb-comments" data-href="{{ request.build_absolute_url}}" data-numposts="5"></div>

                        <i><b>  {{ total_likes }} Like{{ total_likes|pluralize }}</b></i>
                   {% if request.user.is_authenticated %}
                    <form action="{% url 'like_post' %}" method="post">
                     {% csrf_token %}
                     {% if is_liked %}
                         <button  class="btn btn-danger btn-sm"  name="post_id" value="{{ post.id }}">
                         <span class="glyphicon glyphicon-thumbs-down"></span>
                        </button>

                    {% else %}
                         <button  class="btn btn-info btn-sm"  name="post_id" value="{{ post.id }}">{{ total_likes }}
                  <span class="glyphicon glyphicon-thumbs-up"></span>
        </button>

                    {% endif %}
                    </form>
                   {% endif %}

                    <!--div class="fb-share-button"  data-href="https://developers.facebook.com/" data-layout="button_count" data-size="large" data-mobile-iframe="true"><a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">Share</a></div-->
                        </div>
                        </div>

                        <!--div class="container-fluid mt-2">
                    <div class="form-group row">
               <form method="post" class="comment-form" action=".">
      {% csrf_token %}
      {{ comment_form.as_p }}
      {% if request.user.is_authenticated %}
        <input type="submit" value="Submit" class="btn btn-outline-success">
      {% else %}
        <input type="submit" value="Submit" class="btn btn-outline-success" disabled>
      {% endif %}
    </form>
  </div>
</div>

{{ comments.count }} Comment{{ comments|pluralize }}
{% for comment in comments %}
  <blockquote class="blockquote">
    <p class="mb-0"><small>{{ comment.content }}</small></p>
    <footer class="blockquote-footer"><small>by <cite title="Source Title">{{ comment.user|capfirst }}</cite></small>
      <button type="button" name="button" class="reply-btn btn btn-outline-dark btn-sm ml-2">Reply</button>
    </footer>
  </blockquote>

  <div class="replied-comments container mt-2" style="display:none;">
    {% for reply in comment.replies.all %}
    <blockquote class="blockquote">
      <p class="mb-0"><small>{{ reply.content }}</small></p>
      <footer class="blockquote-footer"><small>by <cite title="Source Title">{{ reply.user|capfirst }}</cite></small>
    </footer>
    </blockquote>
    {% endfor %}
    <div class="form-group row">
      <form method="post" class="reply-form" action="">
        {% csrf_token %}
        <input type="hidden" name="comment_id" value="{{ comment.id }}">
        {{ comment_form.as_p }}
        {% if request.user.is_authenticated %}
          <input type="submit" value="Submit" class="btn btn-outline-success">
        {% else %}
          <input type="submit" value="Submit" class="btn btn-outline-success" disabled>
        {% endif %}
      </form>
    </div>
  </div>
{% endfor %}

                    </div-->





 </div>


</div>
                      </div>




            </div>

        </div>
    </div>
   </body>